#!/bin/bash
action=$1
target=$2
args=$@

BASE_DIR=/root/chatgpt-share-web

function usage() {
    echo "share 控制脚本"
    echo
    echo "Usage: "
    echo "  ./sharectl [COMMAND] [ARGS...]"
    echo "  ./sharectl --help"
    echo
    echo "Commands: "
    echo "  update              更新share，会拉取最新镜像"
    echo "  restart             强制重启share服务，会拉取最新镜像"
    echo "  stop                停止share服务"
    echo "  fix-redis           修复redis的AOF损坏（redis反复崩溃重启时使用）"
}
function update() {
    cd $BASE_DIR
    # ./deploy.sh
    docker compose pull
    docker compose up -d --remove-orphans
}
function restart() {
    cd $BASE_DIR
    # ./restart.sh
    docker compose pull
    docker compose up -d --remove-orphans --force-recreate
}
function stop() {
    cd $BASE_DIR
    docker compose down
}
function fix_redis() {
    cd $BASE_DIR
    ./fix-redis-aof.sh
}

function main() {
    case "${action}" in
    update)
        update
        ;;
    restart)
        restart
        ;;
    stop)
        stop
        ;;
    fix-redis)
        fix_redis
        ;;
    help)
        usage
        ;;
    --help)
        usage
        ;;
    "")
        usage
        ;;
    *)
        echo "不支持的参数，请使用 help 或 --help 参数获取帮助"
        ;;
    esac
}
main
